run_name: TZbase_GM_Standard_TL
epochs: 500
batch_size: 512
image_size: 64
lr: 0.00000001 #1e-8 was the final lr used in the TransferZ baseline with scheduler
scheduler: true
dataset: 1
model_description: "TL on input layer and Classifier part of ResNet model with 2-layer classifier"
optimizer_type: "adam"
activation: "silu" # This activation is for the classifier
dropout_rate: 0.5
nested: false
hidden_dims: [512, 256]
memory_limit: 30
spectra_mode: false
save_frequency: 1
data_fraction: 1.0
early_stopping: true

# LoRA parameters
lora_flag: false
# lora_type: "full"
# lora_r: 4c
# lora_alpha: 16
# lora_dropout: 0.1

# Transfer learning
transfer_learn: true
transfer_learn_mode: "unfreeze"
unfreeze_layers: ["classifier.0", "classifier.3", "classifier.6", "features.0"]  # Unfreeze input layer and classifier layers

# Checkpoint path (optional)
checkpoint: 'add_your_checkpoint_file.pth'
